### ISSUE TITLE
using istanbul and getting coverage-results back into grunt

### ISSUE THREAD

**Issue by renegat4** [gruntjs/grunt-contrib-jasmine#261] opened 2017-08-30 20:00 UTC
I write an angularjs-app and would like to have code coverage reports from my jasmine tests.

The  problem is, the tests are run in phantomjs which is an other process with its own global object and after running the tests grunt-istanbul cant see the results and complains: 'No coverage information was collected'.

I modified the sources of grunt-contrib-jasmine (only 8 simple lines) to fix this issue.

But i feel i must be missing something. Surely someone allready created a solution and i simply cant find it.

If you are interested i will be happy to make a PR.

**Comment by Boosten** [comment] 2017-11-13 12:15
Can you share your current setup? Are you using the correct setup? Because I’m succesfully using grunt-contrib-jasmine with coverage generation via grunt-template-jasmine-istanbul 

https://github.com/maenu/grunt-template-jasmine-istanbul

**Comment by steveoh** [comment] 2018-10-19 01:01
duplicate of #281

**Closed by steveoh** 2018-10-19 01:01 UTC
